using UnityEngine;

public class Turret : MonoBehaviour
{
    [SerializeField] private Transform headTransform;
    [SerializeField] private TurretBullet turretBulletPrefab;
    [SerializeField] private Transform shootPointTransform;


    private float shootTimer;
    

    public void Update()
    {
        if (!IsPlayerInRange())
        {
            return;
        }

        Vector2 aimDirection = (Lander.Instance.transform.position - headTransform.position).normalized;
        headTransform.right = aimDirection;


        shootTimer -= Time.deltaTime;
        if (shootTimer < 0) {
            float shootTimerMax = 1.5f;
            shootTimer = shootTimerMax;

          TurretBullet turretBullet = Instantiate(turretBulletPrefab, shootPointTransform.position, Quaternion.identity);
            turretBullet.Setup(aimDirection);
        }


    }


    private bool IsPlayerInRange()
    {
        float range = 14f;
        return Vector2.Distance(transform.position, Lander.Instance.transform.position) < range;
    }

}
